### PR TITLE
Match scale with the image/labels

### PR DESCRIPTION
**Pull request by ilyasdc**
If the image masks contain  pixel size, napari modifies the scale factor upon loading. Your plugin doesn't take into account this scale factor, this PR fixes that (entirely, I hope)

### CODE REVIEW

**Comment by maweigert** [comment]
Good catch, thanks! (I did some minor changes)

**Comment by maweigert** [comment]
It is! Maybe too easy, as I think the patch got deleted before I could merge it :)

**Comment by ilyasdc** [comment]
> It is! Maybe too easy, as I think the patch got deleted before I could merge it :)

Well, maybe I should learn how it works then🤦
I undeleted the fork, is it working now ?

**Comment by maweigert** [comment]
it is, perfect! Thanks!!

**Comment by bentaculum** [comment]
Thanks @ilyasdc 🚀

**Pull request merged**
